#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import re
import sys

def main():
    path_aosp = sys.argv[1]
    path_project = sys.argv[2]
    if re.search('^platform/', path_project) != None:
        path_project = re.sub('^platform/', '', path_project)

    local_aosp = os.path.join(path_aosp, path_project)
    if os.access(local_aosp, os.R_OK):
        os.system("git remote add aosp {}".format(local_aosp))

if __name__ == "__main__":
    main()
