#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import argparse
import os
import select
import smtplib
import socket
import sys

__author__ = 'Chang, Yu-Heng'

def get_arguments():
    parser = argparse.ArgumentParser(description='Quickly send an email. \
            Mail contents would be read from standard input and it could be empty.')
    parser.add_argument('-s', '--sender', metavar='SENDER',
            default='anonymous@anonymous.org', help="sender's email")
    parser.add_argument('-r', '--recipients', metavar='RECIPIENTS', nargs='+',
            required=True, help="recipients' email")
    parser.add_argument('-j', '--subject', metavar='SUBJECT', required=True,
            help='mail subject')
    parser.add_argument('--smtp', metavar='MAIL_SERVER',
            default='msa.hinet.net', help='server address for SMTP service')
    args = parser.parse_args()
    return args

def sendmail(args):
    msg = MIMEMultipart()
    if select.select([sys.stdin], [], [], 0)[0]:
        msg.attach(MIMEText(sys.stdin.read()))
    msg['To'] = ','.join(args.recipients)
    msg['from'] = args.sender
    msg['subject'] = args.subject

    try:
        s = smtplib.SMTP()
        s.connect(args.smtp)
        s.sendmail(args.sender, args.recipients, msg.as_string())
        s.quit()
    except Exception as e:
        print(e, file=sys.stderr)
        exit(1)

def main():
    sendmail(get_arguments())

if __name__ == '__main__':
    main()
