#!/usr/bin/env bash

backup_enabled=0
backup_suffix=".bak"
working_suffix=".source_code_formatter.working"

if [ "$1" = "--backup" ]; then
    backup_enabled=1
    shift
fi

for f in "$1"; do
    if [[ -f "$f" ]]; then
        if [[ $backup_enabled == "1" ]]; then
            cp "$f" "$f$backup_suffix"
        fi

        if [[ `head -c 3 "$f"` == $'\xef\xbb\xbf' ]]; then
            # file exists and has UTF-8 BOM
            cp "$f" "$f$working_suffix"
            tail -c +4 "$f$working_suffix" > "$f"
            rm "$f$working_suffix"
            echo "Removed BOM from \"$f\"."
        fi

        sed -i 's///g' "$f"

        sed -i 's/\t/\ \ \ \ /g' "$f"
        sed -i 's/\ \+$//g' "$f"
    fi
done
