#!/usr/bin/env bash

cmd="`basename "$0"`"
exdirs="( -name .repo -o -name .hg -o -name .git -o -name .svn )"
exfiles="( -name cscope.* )"

fts=""

if [ $cmd = "jgrep" ]; then
    fts="-name *.java"
elif [ $cmd = "cppgrep" ]; then
    fts="( -name *.c -o -name *.cc -o -name *.cpp -o -name *.h )"
elif [ $cmd = "cppgrep" ]; then
    fts="( -name *.c -o -name *.cc -o -name *.cpp -o -name *.h )"
fi

find . -type d $exdirs -prune -o -type f $exfiles -o -type f $fts -print0 \
    | xargs --null grep --color --with-filename --line-number \
    --binary-files=without-match "$@"
